# Generated by Django 2.2.9 on 2020-03-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(max_length=50, verbose_name='identificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('gender', models.CharField(max_length=1, verbose_name='Sexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.CharField(max_length=100, verbose_name='Demanda')),
                ('date', models.DateField(verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='demand.Category', verbose_name='Categoria')),
                ('document', models.ForeignKey(db_column='document_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.Document', verbose_name='Arquivo')),
                ('people', models.ForeignKey(db_column='people_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='demand.People', verbose_name='Usuario')),
            ],
        ),
    ]
